title: "[Q&A] "
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
      placeholder: I'm trying to figure out how to...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please provide any relevant context (e.g., error messages, environment details).
    validations:
      required: false
